"""
Gitea push-webhook receiver.

Gitea POSTs a JSON payload to a configured URL whenever a branch is pushed.
This module verifies the delivery's HMAC-SHA256 signature and, when the
pushed branch matches a ticket's dev-environment branch
(``ticket/{provider}/{ticket_id}``, the convention
``BranchManager.make_branch_name()`` produces), triggers an instant
refresh via ``DevEnvironmentManager.refresh()``.

The actual hot-reload mechanism needs no new logic here: refresh() runs
``git fetch && git reset --hard`` inside the running container, and the
container's own inotify-restart-loop / HMR watcher (already implemented
in ``src/core/dev_environment.py``) picks up the file change automatically.
This receiver's only job is triggering that pull the instant Gitea
reports a push — the "instant" alternative to polling.

Setup
-----
Configured automatically by ``ProjectSyncWorkflow.ensure_repo()`` (via
``GiteaManager.create_webhook()``) once ``GITEA_WEBHOOK_TOKEN`` and a
target URL are set — no manual Gitea UI steps needed.

Set the ``GITEA_WEBHOOK_TOKEN`` env var (auto-generated by
``scripts/setup.sh``); the receiver validates the ``X-Gitea-Signature``
header, an HMAC-SHA256 hex digest of the raw request body using this
shared secret. Leave unset to skip verification (development only — not
recommended once Marcus is reachable from outside localhost).
"""

import hashlib
import hmac
import json
import logging
import os
import re
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

# Matches the ticket branch naming convention
# BranchManager.make_branch_name() produces: ticket/{provider}/{ticket_id}
_TICKET_BRANCH_RE = re.compile(r"^ticket/([^/]+)/(.+)$")
_BRANCH_REF_RE = re.compile(r"^refs/heads/(.+)$")


class GiteaWebhookReceiver:
    """Verifies Gitea push-webhook deliveries and triggers dev-env refresh.

    Parameters
    ----------
    dev_env_manager : Any
        A ``DevEnvironmentManager``-shaped object exposing an async
        ``refresh(ticket_id, provider) -> bool`` method. Typed loosely
        (duck-typed) to avoid importing ``DevEnvironmentManager`` just
        for a type hint.
    secret : Optional[str]
        Shared HMAC secret. When set, incoming deliveries must carry a
        matching ``X-Gitea-Signature`` header; mismatches are rejected.
        Defaults to the ``GITEA_WEBHOOK_TOKEN`` environment variable.
    """

    def __init__(self, dev_env_manager: Any, secret: Optional[str] = None) -> None:
        """Initialise the receiver."""
        self._dev_env = dev_env_manager
        self._secret = secret or os.getenv("GITEA_WEBHOOK_TOKEN")

    async def handle_request(
        self, body: bytes, *, signature: Optional[str] = None
    ) -> bool:
        """Verify and process a raw Gitea push-webhook request body.

        Parameters
        ----------
        body : bytes
            Raw HTTP request body (JSON).
        signature : Optional[str]
            Value of the ``X-Gitea-Signature`` header, if present.

        Returns
        -------
        bool
            ``True`` if the delivery was accepted (including deliveries
            that are well-formed but not actionable, e.g. a tag push or
            a branch with no running dev environment). ``False`` if
            rejected — bad signature, malformed body, or the refresh
            itself failed.
        """
        if not self._validate_signature(body, signature):
            logger.warning("Gitea webhook rejected: invalid signature")
            return False

        try:
            payload: Dict[str, Any] = json.loads(body)
        except json.JSONDecodeError as exc:
            logger.warning("Gitea webhook: malformed JSON — %s", exc)
            return False

        ref = payload.get("ref", "")
        repo = payload.get("repository") or {}
        repo_name = repo.get("name", "")

        branch_match = _BRANCH_REF_RE.match(ref)
        if not branch_match:
            logger.debug("Gitea webhook: ref %r is not a branch push — ignoring", ref)
            return True
        branch_name = branch_match.group(1)

        ticket_match = _TICKET_BRANCH_RE.match(branch_name)
        if not ticket_match:
            logger.debug(
                "Gitea webhook: branch %r doesn't match ticket/<provider>/<id> — ignoring",
                branch_name,
            )
            return True
        provider, ticket_id = ticket_match.group(1), ticket_match.group(2)

        try:
            refreshed = await self._dev_env.refresh(ticket_id, provider)
        except Exception:
            logger.exception(
                "Error refreshing dev environment for ticket=%s provider=%s",
                ticket_id,
                provider,
            )
            return False

        if refreshed:
            logger.info(
                "Gitea webhook -> refreshed dev env (repo=%s, ticket=%s, provider=%s)",
                repo_name,
                ticket_id,
                provider,
            )
        else:
            logger.debug(
                "Gitea webhook: no running dev env for ticket=%s provider=%s (repo=%s)",
                ticket_id,
                provider,
                repo_name,
            )
        return True

    def _validate_signature(self, body: bytes, signature: Optional[str]) -> bool:
        """Return True if the HMAC-SHA256 signature matches the shared secret.

        Parameters
        ----------
        body : bytes
            Raw request body the signature was computed over.
        signature : Optional[str]
            The ``X-Gitea-Signature`` header value, if present.

        Returns
        -------
        bool
            True if valid (or signature checking is disabled).
        """
        if not self._secret:
            return True  # validation disabled
        if not signature:
            return False
        expected = hmac.new(
            self._secret.encode("utf-8"), body, hashlib.sha256
        ).hexdigest()
        # Compare as bytes, not str: hmac.compare_digest() raises TypeError
        # on a str containing non-ASCII characters, and the attacker
        # controls `signature` (it comes from the raw X-Gitea-Signature
        # header, decoded latin-1 by Starlette — bytes 0x80-0xFF become
        # non-ASCII code points). Comparing UTF-8 bytes never raises on
        # content, so a hostile header cleanly fails verification instead
        # of crashing the request with a 500 (see the identical fix and
        # rationale in src/core/agent_auth.py's bearer-token comparison).
        return hmac.compare_digest(
            expected.encode("utf-8"), signature.encode("utf-8")
        )
